### ISSUE TITLE
报错：UnicodeDecodeError: 'utf8' codec can't decode byte 0xd7 in position 60。。。。

### ISSUE THREAD

**Issue by hkxueqi** [Lewiswu1209/fingerprint#1]
。。。。。
        [-]     识别到:nginx, 在位置:/
Traceback (most recent call last):
  File "fingerprint.py", line 52, in <module>
    rs_cms  = cms.scan(sys.argv[1], True)
  File "E:\sectool\InfoCollect\fingerprint-master\lib\fingerprint.py", line 77, in scan
    matched = self.check(body, header, self.fingerprintdb[path_url], fastMode)
  File "E:\sectool\InfoCollect\fingerprint-master\lib\fingerprint.py", line 48, in check
    isMatch = re.search(finger['pattern'], body.decode(encoding='UTF-8'), re.IGNORECASE)
  File "C:\Program Files (x86)\python2\lib\encodings\utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xd7 in position 60: invalid continuation byte

**Comment by lewiswu1209** [comment]
哈哈~当时偷了个懒，原来还真有UTF-8没法decode的，开来我需要探测编码了

**Comment by lewiswu1209** [comment]
我在decode之前加了检测编码的代码，不过没有经过充分测试，所以暂时没有合并分支issue1，帮我试试这个分支能不能解决你遇到的问题。

**Comment by xueqi-hk** [comment]
好的，明天我试一下------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;lewiswu1209&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年6月7日(星期天) 凌晨0:21
收件人:&nbsp;&quot;lewiswu1209/fingerprint&quot;<fingerprint@noreply.github.com&gt;;
抄送:&nbsp;&quot;xueqi-hk&quot;<1149161736@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [lewiswu1209/fingerprint] 报错：UnicodeDecodeError: &#39;utf8&#39; codec can&#39;t decode byte 0xd7 in position 60。。。。 (#1)

**Comment by hkxueqi** [comment]
我在win测试了，报错了新的信息
Traceback (most recent call last):
  File "fingerprint.py", line 50, in <module>
    rs_cms  = cms.scan(sys.argv[1], True)
  File "D:\Users\Administrator\Desktop\fingerprint-issue1\lib\fingerprint.py", line 82, in scan
    response = urllib2.urlopen(request)
  File "C:\Program Files (x86)\python2\lib\urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Program Files (x86)\python2\lib\urllib2.py", line 429, in open
    response = self._open(req, data)
  File "C:\Program Files (x86)\python2\lib\urllib2.py", line 447, in _open
    '_open', req)
  File "C:\Program Files (x86)\python2\lib\urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "C:\Program Files (x86)\python2\lib\urllib2.py", line 1241, in https_open
    context=self._context)
  File "C:\Program Files (x86)\python2\lib\urllib2.py", line 1198, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 11001] getaddrinfo failed>

**Comment by lewiswu1209** [comment]
这个……是不是你IP被封了吧，爬虫爬不下来页面，如果方便的话，能提供下你测试的站点么？我好排除下问题

**Comment by hkxueqi** [comment]
> 这个……是不是你IP被封了吧，爬虫爬不下来页面，如果方便的话，能提供下你测试的站点么？我好排除下问题

我用的自己博客，访问是没问题的，也没有waf  url:www.idxueqi.cn
